version: '3.8'

services:
  app:
    container_name: authentication_service
    build: .
    ports:
      - "${APP_PORT}:8080"
    environment:
      APP_PORT: ${APP_PORT}
      JWT_SECRET: ${JWT_SECRET}
      AES_ENCRYPT: ${AES_ENCRYPT}
      AES_FIXED_IV: ${AES_FIXED_IV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_SSLMODE: ${DB_SSLMODE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CDN_URL: ${CDN_URL}
      NATS_URL: ${NATS_URL}
    restart: always
